### PR TITLE
zh-cn

### PR DESCRIPTION
**Pull request by zer0Kerbal**
updates #11 @thank you @Peter-JY [Peter-JY](https://github.com/Peter-JY)
updates #6 

slight changes to zh-cn.cfg to fix formatting
reverts changes to license so can be merged into dev branch

### CODE REVIEW

**Review by zer0Kerbal — COMMENTED** [review]
🧧

**Comment by Peter-JY** [comment]
By the way, You do this just under CC-BY-NC-SD 4.0, or you have gotten the permission from the original author?

**Comment by zer0Kerbal** [comment]
> By the way, You do this just under CC-BY-NC-SD 4.0, or you have gotten the permission from the original author?

I have explicit permission from Baeile., and this is `CC BY-ND 3.0 Unported`, except for files explicitly stating other wise.

Images, textures are still `All Rights Reserved`, which includes the HeroLogo.

https://zer0kerbal.github.io/Taerobee/LegalMumboJumbo.html

**Comment by zer0Kerbal** [comment]
I have made the localization files more permissive, and obviously granted license to the translators to those files, and those files only.

I am following the wishes of the original author.

**Comment by zer0Kerbal** [comment]
here is the header of the <zh-ch.cfg> file:
```
// zh-cn.cfg v1.0.0.1
// Taerobee (TBEE)
// created: 04 Feb 2023
// updated: 06 Feb 2923

// THIS FILE:
//   CC BY-SA 4.0 by Peter-JY, and [zer0Kerbal](https://github.com/zer0Kerbal)
//   translated courtesy of [Peter-JY](https://github.com/Peter-JY)

// #仅限原版 For stock only

Localization 
{
```

https://github.com/zer0Kerbal/Taerobee/blob/1.4.4.0-release/GameData/Taerobee/Localization/zh-cn.cfg

**Comment by Peter-JY** [comment]
Oh I know. But there's a thing to point out, CC permission can't be repealled. Beale turly changed the lincense to All Rrights Reserved, but versions updated before is still in CC-BY-NC-SA 4.0, so I use that lincense.

**Comment by Peter-JY** [comment]
And I updated zh-tw.cfg, and fixed 2 tanslating errors in zh-cn.cfg meanwhile. Need I pull a new request?

**Comment by zer0Kerbal** [comment]
@Peter-JY Kindly post (under KSP FORUM posting rules) the chinese translation. 

Concerning your other concern: Show me the evidence that this was EVER anything but ARR - there isn't any independent proof.

You have your branch, which claims a license, but doesn't even state what you promised to state. See link (https://zer0kerbal.github.io/Taerobee/LegalMumboJumbo.html)

kindly post independent evidence backing your statements are backed with evidence.

**Pull request merged**
