### PR TITLE
zh-tw.cfg  ! important statement included !

### PR DESCRIPTION
**Pull request by Peter-JY**
I'm sorry to pull all my changes because the limitation of time.
However, it's __NOT TAIWANESE BUT TRADITIONAL CHINESE, NOT 国语 BUT 繁体中文__!!! This thing CAN NOT be changed. Taiwan is a part of China! This __MUST__ be fixed!
A solemn statement is made here.

### CODE REVIEW

**Comment by Peter-JY** [comment]
Maybe you won’t notice what I said before. Beale’s mod is originally posted under CC-BY-NC-SA 4.0 according to the information I got. If it’s true, it’s against the license you mentioned in forum. You’ve got the author’s permission to update, so I think you’d better check the license once again. By the way, translations I contributed is under the same license of Beale’a original one.

**Comment by zer0Kerbal** [comment]
kindly post into the KSP forum both of these.


Won't accept due to:
1. licensing
2. political statements. zer0Kerbal is a apolitical entity.

**Comment by zer0Kerbal** [comment]
> Maybe you won’t notice what I said before. Beale’s mod is originally posted under CC-BY-NC-SA 4.0 according to the information I got. If it’s true, it’s against the license you mentioned in forum. You’ve got the author’s permission to update, so I think you’d better check the license once again. By the way, translations I contributed is under the same license of Beale’a original one.

Incorrect in your statements concerning license.

**Comment by Peter-JY** [comment]
很抱歉。观念不同。至于这一版翻译，我也并不精通如何做到信雅达，就让它消失在历史的云烟里好了。
也很抱歉，或许，让你误解了我的意思，认为有政治目的。但无论如何这一称谓是我的底线。
我认为我的英语水平可能不足以让我准确表达我所表达的意思。
如果我还有更新的意愿，我会重新unarchive我的repository，并进行我的修改。所有从您的repository里fork的内容已经全部删除。以后的更改按照原作者修改为all rights reserved之前最后一个CC协议执行(根据CC协议的不可撤回性)。
愿您诸事顺利。

**Pull request closed without merging**
