### PR TITLE
Create SlimJim.cfg

### PR DESCRIPTION
**Pull request by AtomikkuSan**
New part.

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
> New part.

Thank you @AtomikkuSan .

What is the purpose of this part and why is it needed? I only ask because I guaranteed the original author @Beale that I wouldn't expand the mod, just update and add compatibility. 

I can see if a part is needed, so am listening.

**Comment by AtomikkuSan** [comment]
It's a smaller, slimmer version of the bumper engine that makes it easier to make an RD-170 like rocket engine that fits within the 1.25m diameter. It also adds more flexibility to the early game.
We could, instead, take the .cfg file out and make a Taerobee Expansion mod that adds this .cfg file back.

**Review by zer0Kerbal — APPROVED** [review]

**Comment by zer0Kerbal** [comment]
thank you @AtomikkuSan 🧧

**Comment by AtomikkuSan** [comment]
always happy to help :)

**Pull request merged**
